### PR TITLE
Extract version values to global configuration flags.

### PR DESCRIPTION
**Pull request by jverkoey**
This is intended to make it easier to understand what needs to change when a version of a given tool needs to be updated.

### CODE REVIEW

**Comment by jverkoey** [comment]
This is reopened from https://github.com/material-foundation/clang-format-ci/pull/9 but on the main repo so that Travis can run CI with the environment variables.

**Comment by romoore** [comment]
I don't see any "secure environment variables" in this change - can you clarify why you abandoned the earlier PR?

**Review by romoore — APPROVED** [review]

**Comment by jverkoey** [comment]
> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by romoore** [comment]
Sorry, I don't think that helps. I still don't get how if it's "encrypted" it can be unencrypted when a PR comes in from the same repo but not from a fork. Does that mean that we'll NEVER be able to submit PRs to this repo from a fork?

**Comment by romoore** [comment]
Since your PR didn't modify any of those variables, it seems like Travis is broken - it can't run presubmits from forks which is the primary workflow for Material open source projects.

**Comment by jverkoey** [comment]
I've filed https://github.com/material-foundation/clang-format-ci/issues/12 to explore fixing this.

**Pull request merged**
